### ISSUE TITLE
Make the links clickable

### ISSUE THREAD

**Issue by Saikat2019** [Saikat2019/HiYo-chat_anonymously#5]
Currently, the links in the chat are displayed as text and aren't clickable. Fix this, so that anyone can click on any message containing a link and can go to the respective address.

**Comment by subhangi2731** [comment]
can you assign this issue to me @Saikat2019

**Comment by aditya28sarin** [comment]
Can you sign me for this?

**Comment by Saikat2019** [comment]
@aditya28sarin I've assigned this to you.

**Comment by aditya28sarin** [comment]
Hey, I have decoded the logic to detect a link in the chat and have created
the function, but I am not able understand your code specially due to lack
of comments, So should I add thw function in the index.js at the bottom and
comment it? You can then takeover from there easily.

Should I start a pull request?

Aditya Sarin

**Comment by Saikat2019** [comment]
Hey, please join the slack workspace here, https://join.slack.com/t/hiyo-kwoc-workspace/shared_invite/zt-jqo85gv6-wYlGzOkao8YP8_90s91cNA , we can discuss it there.
And please keep your work on a separate branch.

**Comment by aditya28sarin** [comment]
Sure, I'll ad it in a separate branch.

Link is saying workspace not found

Aditya Sarin

**Comment by Saikat2019** [comment]
You can get the slack invite link also in the readme
